apiVersion: apps/v1
kind: Deployment
metadata:
  name: goals-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goals-service
  template:
    metadata:
      labels:
        app: goals-service
    spec:
      containers:
        - name: goals-service
          image: goals-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/goals_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "myfinances_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "myfinances_pass"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
            - name: SERVICES_ACCOUNT_SERVICE_URL
              value: "http://account-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: goals-service
spec:
  selector:
    app: goals-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
