apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 150
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 768Mi
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            
            # Desactivar Eureka
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/user_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "myfinances_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "myfinances_pass"
            
            # Keycloak
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak:8080"
            - name: KEYCLOAK_REALM
              value: "myfinances-realm"
            - name: KEYCLOAK_RESOURCE
              value: "myfinances-app"
            - name: KEYCLOAK_CREDENTIALS_SECRET
              value: ""
            - name: KEYCLOAK_ADMIN_USERNAME
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"

            # Account service URL for Feign
            - name: SERVICES_ACCOUNT_SERVICE_URL
              value: "http://account-service:8081"

            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
