spring.application.name=user-service

# Fallback minimo si Config Server no responde.
# En produccion, el Config Server (GitHub) tiene la config completa
# incluyendo Keycloak, datasource, services URLs, etc.
server.port=8084
spring.jpa.hibernate.ddl-auto=update

