spring.application.name=goals-service

# Fallback minimo si Config Server no responde.
# En produccion, el Config Server (GitHub) tiene la config completa.
server.port=8085
spring.jpa.hibernate.ddl-auto=update
spring.cloud.openfeign.circuitbreaker.enabled=true

